=== dionusos/dipterv.big-dataanalyzer/xsd/src/main/resources/metadata.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="metadata">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="BaseMetricCalculation" name="baseMetricCalculation" maxOccurs="unbounded" minOccurs="0"/>
                <xs:element type="KpiDef" name="kpi" maxOccurs="unbounded" minOccurs="0" />
                <xs:element type="DimensionDef" name="dimension" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="BaseMetricCalculation">
        <xs:sequence>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="xs:string" name="calculation"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="KpiDef">
        <xs:sequence>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="xs:string" name="friendlyName"/>
            <xs:element type="Column" name="column" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element type="OfferedMetric" name="offeredMetric" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Column">
        <xs:sequence>
            <xs:element type="xs:string" name="postfix"/>
            <xs:element type="DataType" name="datatype"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="OfferedMetric">
        <xs:sequence>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="xs:string" name="calculation"/>
            <xs:element type="xs:string" name="friendlyName" minOccurs="0"/>
            <xs:element type="xs:string" name="description" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DimensionDef">
        <xs:sequence>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="xs:string" name="friendlyName" minOccurs="0"/>
            <xs:element type="DataType" name="datatype"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="DataType">
        <xs:restriction base="xs:string">
            <xs:pattern value="INT16|INT32|INT64|FLOAT|STRING|BOOLEAN"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== dionusos/dipterv.big-dataanalyzer/example/src/main/resources/carsharing/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../../../xsd/src/main/resources/metadata.xsd">
    <kpi>
        <name>battery_level</name>
        <friendlyName>Battery level</friendlyName>
        <offeredMetric>
            <name>avg</name>
            <calculation>sum(${kpi})/sum(${table}samples_sum)</calculation>
            <friendlyName>Average</friendlyName>
            <description></description>
        </offeredMetric>
        <column>
            <postfix></postfix>
            <datatype>INT8</datatype>
        </column>
    </kpi>
    <kpi>
        <name>estimated_km</name>
        <friendlyName>Estimated kilometers</friendlyName>
        <offeredMetric>
            <name>sum</name>
            <calculation>sum(${kpi})</calculation>
            <friendlyName>Sum</friendlyName>
            <description></description>
        </offeredMetric>
        <offeredMetric>
            <name>avg</name>
            <calculation>sum(${kpi})/sum(${table}samples_sum)</calculation>
            <friendlyName>Average</friendlyName>
            <description></description>
        </offeredMetric>
        <column>
            <postfix></postfix>
            <datatype>INT32</datatype>
        </column>
    </kpi>
    <kpi>
        <name>samples</name>
        <friendlyName>Number of cars</friendlyName>
        <offeredMetric>
            <name>sum</name>
            <calculation>sum(${kpi}_sum)</calculation>
            <friendlyName>Sum</friendlyName>
            <description></description>
        </offeredMetric>
        <column>
            <postfix>sum</postfix>
            <datatype>INT8</datatype>
        </column>
    </kpi>
    <dimension>
        <name>start_time</name>
        <friendlyName>Timestamp</friendlyName>
        <datatype>INT32</datatype>
    </dimension>
    <dimension>
        <name>timestamp</name>
        <friendlyName>Timestamp</friendlyName>
        <datatype>INT32</datatype>
    </dimension>
    <dimension>
        <name>company</name>
        <friendlyName>Company</friendlyName>
        <datatype>STRING</datatype>
    </dimension>
    <dimension>
        <name>address</name>
        <friendlyName>Address</friendlyName>
        <datatype>STRING</datatype>
    </dimension>
    <dimension>
        <name>battery_state</name>
        <friendlyName>battery_state</friendlyName>
        <datatype>STRING</datatype>
    </dimension>
    <dimension>
        <name>battery_state_desc</name>
        <friendlyName>battery_state_desc</friendlyName>
        <datatype>STRING</datatype>
    </dimension>
    <dimension>
        <name>color</name>
        <friendlyName>color</friendlyName>
        <datatype>STRING</datatype>
    </dimension>
    <dimension>
        <name>color_desc</name>
        <friendlyName>color_desc</friendlyName>
        <datatype>STRING</datatype>
    </dimension>
    <dimension>
        <name>distance</name>
        <friendlyName>distance</friendlyName>
        <datatype>INT8</datatype>
    </dimension>
    <dimension>
        <name>doors</name>
        <friendlyName>doors</friendlyName>
        <datatype>INT8</datatype>
    </dimension>
    <dimension>
        <name>gps_lat</name>
        <friendlyName>gps_lat</friendlyName>
        <datatype>DOUBLE</datatype>
    </dimension>
    <dimension>
        <name>gps_long</name>
        <friendlyName>gps_long</friendlyName>
        <datatype>DOUBLE</datatype>
    </dimension>
    <dimension>
        <name>make</name>
        <friendlyName>make haze</friendlyName>
        <datatype>STRING</datatype>
    </dimension>
    <dimension>
        <name>make_desc</name>
        <friendlyName>make_desc</friendlyName>
        <datatype>STRING</datatype>
    </dimension>
    <dimension>
        <name>max_range</name>
        <friendlyName>max_range</friendlyName>
        <datatype>INT8</datatype>
    </dimension>
    <dimension>
        <name>model</name>
        <friendlyName>model</friendlyName>
        <datatype>STRING</datatype>
    </dimension>
    <dimension>
        <name>plate_number</name>
        <friendlyName>plate_number</friendlyName>
        <datatype>STRING</datatype>
    </dimension>
    <dimension>
        <name>seats</name>
        <friendlyName>seats</friendlyName>
        <datatype>INT8</datatype>
    </dimension>
    <dimension>
        <name>state</name>
        <friendlyName>state</friendlyName>
        <datatype>STRING</datatype>
    </dimension>
    <dimension>
        <name>state_desc</name>
        <friendlyName>state_desc</friendlyName>
        <datatype>STRING</datatype>
    </dimension>
    <dimension>
        <name>variant</name>
        <friendlyName>variant</friendlyName>
        <datatype>STRING</datatype>
    </dimension>
    <dimension>
        <name>vehicle_id</name>
        <friendlyName>vehicle_id</friendlyName>
        <datatype>STRING</datatype>
    </dimension>
    <!--aggregator.statistics-->
    <kpi>
        <name>rownum</name>
        <friendlyName>Number of rows</friendlyName>
        <offeredMetric>
            <name>sum</name>
            <calculation>sum(rownum_sum)</calculation>
            <friendlyName>Sum</friendlyName>
            <description></description>
        </offeredMetric>
        <column>
            <postfix>sum</postfix>
            <datatype>INT32</datatype>
        </column>
    </kpi>
    <dimension>
        <name>schema</name>
        <friendlyName>Schema</friendlyName>
        <datatype>STRING</datatype>
    </dimension>
    <dimension>
        <name>table</name>
        <friendlyName>Table</friendlyName>
        <datatype>STRING</datatype>
    </dimension>
    <dimension>
        <name>start_time</name>
        <friendlyName>Start time</friendlyName>
        <datatype>INT32</datatype>
    </dimension>

</metadata>

=== dionusos/dipterv.big-dataanalyzer/example/src/main/resources/example1/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../../../xsd/src/main/resources/metadata.xsd">
    <kpi>
        <name>temperature</name>
        <friendlyName>Temperature</friendlyName>
        <offeredMetric>
            <name>min</name>
            <calculation>min(temperaturemin)</calculation>
            <friendlyName>Minimum</friendlyName>
            <description></description>
        </offeredMetric>
        <offeredMetric>
            <name>max</name>
            <calculation>max(temperaturemax)</calculation>
            <friendlyName>Maximum</friendlyName>
            <description></description>
        </offeredMetric>
        <column>
            <postfix>min</postfix>
            <datatype>FLOAT</datatype>
        </column>
        <column>
            <postfix>max</postfix>
            <datatype>FLOAT</datatype>
        </column>
    </kpi>
    <kpi>
        <name>precipitation</name>
        <friendlyName>Precipitation</friendlyName>
        <offeredMetric>
            <name>sum</name>
            <calculation>sum(precipitation)</calculation>
            <friendlyName></friendlyName>
            <description></description>
        </offeredMetric>
        <column>
            <postfix></postfix>
            <datatype>FLOAT</datatype>
        </column>
    </kpi>
    <kpi>
        <name>snowfall</name>
        <friendlyName>Snowfall</friendlyName>
        <offeredMetric>
            <name>sum</name>
            <calculation>sum(snowfall)</calculation>
            <friendlyName></friendlyName>
            <description></description>
        </offeredMetric>
        <column>
            <postfix></postfix>
            <datatype>FLOAT</datatype>
        </column>
    </kpi>
    <kpi>
        <name>snowdepth</name>
        <friendlyName>Snowdepth</friendlyName>
        <offeredMetric>
            <name>sum</name>
            <calculation>sum(snowdepth)</calculation>
            <friendlyName></friendlyName>
            <description></description>
        </offeredMetric>
        <column>
            <postfix></postfix>
            <datatype>FLOAT</datatype>
        </column>
    </kpi>
    <dimension>
        <name>date</name>
        <friendlyName>Date</friendlyName>
        <datatype>STRING</datatype>
    </dimension>
    <dimension>
        <name>fog</name>
        <friendlyName>Fog</friendlyName>
        <datatype>BOOLEAN</datatype>
    </dimension>
    <dimension>
        <name>fogheavy</name>
        <friendlyName>Heavy fog</friendlyName>
        <datatype>BOOLEAN</datatype>
    </dimension>
    <dimension>
        <name>mist</name>
        <friendlyName>Mist</friendlyName>
        <datatype>BOOLEAN</datatype>
    </dimension>
    <dimension>
        <name>rain</name>
        <friendlyName>Rain</friendlyName>
        <datatype>BOOLEAN</datatype>
    </dimension>
    <dimension>
        <name>fogground</name>
        <friendlyName>Fog ground</friendlyName>
        <datatype>BOOLEAN</datatype>
    </dimension>
    <dimension>
        <name>ice</name>
        <friendlyName>Ice</friendlyName>
        <datatype>BOOLEAN</datatype>
    </dimension>
    <dimension>
        <name>glaze</name>
        <friendlyName>Glaze</friendlyName>
        <datatype>BOOLEAN</datatype>
    </dimension>
    <dimension>
        <name>drizzle</name>
        <friendlyName>Drizzle</friendlyName>
        <datatype>BOOLEAN</datatype>
    </dimension>
    <dimension>
        <name>snow</name>
        <friendlyName>Snow</friendlyName>
        <datatype>BOOLEAN</datatype>
    </dimension>
    <dimension>
        <name>freezingrain</name>
        <friendlyName>Freezing rain</friendlyName>
        <datatype>BOOLEAN</datatype>
    </dimension>
    <dimension>
        <name>smokehaze</name>
        <friendlyName>Smoke haze</friendlyName>
        <datatype>BOOLEAN</datatype>
    </dimension>
    <dimension>
        <name>thunder</name>
        <friendlyName>Thunder</friendlyName>
        <datatype>BOOLEAN</datatype>
    </dimension>
    <dimension>
        <name>highwind</name>
        <friendlyName>High wind</friendlyName>
        <datatype>BOOLEAN</datatype>
    </dimension>
    <dimension>
        <name>hail</name>
        <friendlyName>Hail</friendlyName>
        <datatype>BOOLEAN</datatype>
    </dimension>
    <dimension>
        <name>blowingsnow</name>
        <friendlyName>Blowing snow</friendlyName>
        <datatype>BOOLEAN</datatype>
    </dimension>
    <dimension>
        <name>dust</name>
        <friendlyName>Dust</friendlyName>
        <datatype>BOOLEAN</datatype>
    </dimension>
    <dimension>
        <name>freezingfog</name>
        <friendlyName>Fog freezing</friendlyName>
        <datatype>BOOLEAN</datatype>
    </dimension>
</metadata>
