=== dionusos/dipterv.big-dataanalyzer/xsd/src/main/resources/schema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="schemas">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="Schema" name="schema" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="Schema">
        <xs:sequence>
            <xs:element type="Table" name="table" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element type="Dimension" name="dimension" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element type="Kpi" name="kpi" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="name"/>
    </xs:complexType>

    <xs:complexType name="Table">
        <xs:attribute type="xs:string" name="name"/>
        <xs:attribute type="xs:integer" name="resolution"/>
    </xs:complexType>

    <xs:complexType name="Kpi">
        <xs:attribute type="xs:string" name="name"/>
        <xs:attribute type="xs:string" name="metric"/>
    </xs:complexType>

    <xs:complexType name="Dimension">
        <xs:attribute type="xs:string" name="name"/>
    </xs:complexType>
</xs:schema>

=== dionusos/dipterv.big-dataanalyzer/example/src/main/resources/carsharing/schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<schemas
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../../../xsd/src/main/resources/schema.xsd">
    <schema name="carsharing">
        <table name="flatted" resolution="1"/>
        <kpi name="battery_level" metric="avg"/>
        <kpi name="estimated_km" metric="avg"/>
        <kpi name="estimated_km" metric="sum"/>
        <kpi name="samples" metric="sum"/>
        <dimension name="timestamp"/>
        <dimension name="company"/>
        <dimension name="address"/>
        <dimension name="battery_state"/>
        <dimension name="battery_state_desc"/>
        <dimension name="color"/>
        <dimension name="color_desc"/>
        <dimension name="distance"/>
        <dimension name="doors"/>
        <dimension name="gps_lat"/>
        <dimension name="gps_long"/>
        <dimension name="make"/>
        <dimension name="make_desc"/>
        <dimension name="max_range"/>
        <dimension name="model"/>
        <dimension name="plate_number"/>
        <dimension name="seats"/>
        <dimension name="state"/>
        <dimension name="state_desc"/>
        <dimension name="variant"/>
        <dimension name="vehicle_id"/>
    </schema>
</schemas>

=== dionusos/dipterv.big-dataanalyzer/example/src/main/resources/example1/schema.xml
<?xml version="1.0" encoding="UTF-8"?>
<schemas
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../../../xsd/src/main/resources/schema.xsd">
    <schema name="example">
        <table name="weather" resolution="1"/>
        <kpi name="temperature" metric="min"/>
        <kpi name="temperature" metric="max"/>
        <dimension name="date"/>
        <dimension name="fog"/>
        <dimension name="fogheavy"/>
        <dimension name="mist"/>
        <dimension name="rain"/>
        <dimension name="fogground"/>
        <dimension name="ice"/>
        <dimension name="glaze"/>
        <dimension name="drizzle"/>
        <dimension name="snow"/>
        <dimension name="freezingrain"/>
        <dimension name="smokehaze"/>
        <dimension name="thunder"/>
        <dimension name="highwind"/>
        <dimension name="hail"/>
        <dimension name="blowingsnow"/>
        <dimension name="dust"/>
        <dimension name="freezingfog"/>
    </schema>
</schemas>
